### ISSUE TITLE
do you have an example repo if using this action with renovate? (only running ec-update on renovate PRs?)

### ISSUE THREAD

**Issue by NullVoxPopuli** [kellyselden/ember-cli-update-action#144]
I've run in to an issue where all me ember-cli-update-action repos didn't update after I updated one of my blueprints.
I've concluded that the ember-cli-update-action is just skipped. 
 example skip: https://github.com/NullVoxPopuli/ember-resources/runs/2944119811?check_suite_focus=true
 
 this is the config I've been using that... I got from somewhere?
 ```yml
 
  ember-cli-update:
    if: github.event_name == 'pull_request' && github.event.pusher.name == 'renovate-bot'
    runs-on: ubuntu-latest
    needs: [tests, try-scenarios]

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GitHubToken }}
      - uses: actions/setup-node@v2
      - uses: kellyselden/ember-cli-update-action@v3
        with:
          autofix_command: npm run lint:fix
          ignore_to: true
```
I have a feeling it has something to do with the `if` condition. but... based on some research, it _should_ work? unless the github apis changed?           :shrug:
